### ISSUE TITLE
real application testing

### ISSUE THREAD

**Issue by mattmccreesh** [mattmccreesh/sHeap#9]
It wouldn't be a bad idea to test on a real program like firefox or chromium. We would need to build from source and disable custom allocation at compile time. We also would likely need to allocate a large address space region upfront for our metadata to support large application.

**Comment by mattmccreesh** [comment]
We should get measurements on benchmarks

**Comment by Flargebla** [comment]
I am working on getting FF built with jemalloc disabled, but am running into issues at the very end of the build process related to the ResourceMonitor.

As for the benchmark testing, I found a couple open source options but most seem old. Hopefully I can at least get one of them working today or tomorrow for testing.

**Comment by mattmccreesh** [comment]
Tested with make, gcc, vim, bash, emacs, ping, and many more applications/binaries/tools
